#!/bin/bash

set -e

ELASTICSEARCH_HOST=$ELASTICSEARCH_PORT_9200_TCP_ADDR
ELASTICSEARCH_PORT=$ELASTICSEARCH_PORT_9200_TCP_PORT

# 替换配置中的环境变量设置
sed -i \
    -e "s|ELASTICSEARCH_HOST|$ELASTICSEARCH_HOST|g" \
    -e "s|ELASTICSEARCH_PORT|$ELASTICSEARCH_PORT|g" \
    -e "s|LOGSTASH_SSL_CERT|$LOGSTASH_SSL_CERT|g" \
    -e "s|LOGSTASH_SSL_KEY|$LOGSTASH_SSL_KEY|g" \
    -e "s|GROK_PATTERNS|$GROK_PATTERNS|g" \
    $LOGSTASH_CONFIG
cat $LOGSTASH_CONFIG

logstash -f $LOGSTASH_CONFIG
