#!/bin/bash

set -e

echo $ELASTICSEARCH_PORT_9200_TCP_ADDR
echo $ELASTICSEARCH_PORT_9200_TCP_PORT
ELASTICSEARCH_HOST=$ELASTICSEARCH_PORT_9200_TCP_ADDR
ELASTICSEARCH_PORT=$ELASTICSEARCH_PORT_9200_TCP_PORT

# 替换配置中的 elasticsearch 设置
sed -i \
    -e "s|ELASTICSEARCH_HOST|$ELASTICSEARCH_HOST|g" \
    -e "s|ELASTICSEARCH_PORT|$ELASTICSEARCH_PORT|g" \
    $LOGSTASH_CONFIG
cat $LOGSTASH_CONFIG
logstash -f $LOGSTASH_CONFIG
